name: monetar_ia
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart:
  speech_to_text: ^6.1.1
  google_generative_ai: ^0.4.5
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.1
  shared_preferences: ^2.0.0
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/logo2.png
    - lib/assets/fundo_metas3.png
    - lib/assets/fundo_receitas2.png
    - lib/assets/fundo_despesas2.png
    - lib/assets/monetar_rosto.png
    - lib/assets/monetar_corpo.png
    - lib/assets/monetar_corpo2.png
    - lib/assets/monetar_home.png
    - lib/assets/profile.png
    - lib/assets/logo_revenue.png
    - lib/assets/logo_expense.png
    - lib/assets/logo_goal.png
    - lib/assets/monetar_speak.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"
