name: monetar_ia
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  fl_chart:
  speech_to_text: ^6.1.1
  google_generative_ai: ^0.4.5
  googleapis: ^13.1.0
  googleapis_auth: ^1.5.1
  shared_preferences: ^2.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - lib/assets/logo.png
    - lib/assets/logo2.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icon.png"
